<?php

return [
    'pt' => 'Português',
    'es' => 'Español',
    'fr' => 'Français',
    'fi' => 'Suomi',
    'en' => 'English',
    'de' => 'Deutsch',
    'it' => 'Italiano',
    'zh_CN' => '简体中文',
    'ko' => '한국어',
    'ja' => '日本語',
    'uk' => 'Українська',
    'ru' => 'Русский',
    'nl' => 'Dutch',
    'vi' => 'Tiếng Việt',
    'tr' => 'Türkçe',
    'ar' => 'العربية',
    'th' => 'ไทย',
    'pl' => 'Polski',
    'id' => 'Bahasa Indonesia',
    'hi' => 'हिन्दी',
    'he' => 'עברית',
];
