<?php

return [
    'accepted' => ' :attribute on hyväksyttävä.',
    'active_url' => ' :attribute ei ole kelvollinen URL-osoite.',
    'after' => ' :attribute:n on oltava päivämäärä :date:n jälkeen.',
    'after_or_equal' => ' :attribute:n on oltava päivämäärä :date:n jälkeen tai yhtä suuri kuin se.',
    'alpha' => ' :attribute saa sisältää vain kirjaimia.',
    'alpha_dash' => ' :attribute saa sisältää vain kirjaimia, numeroita, väliviivoja ja alaviivoja.',
    'alpha_num' => ' :attribute saa sisältää vain kirjaimia ja numeroita.',
    'array' => ' :attribute:n on oltava taulukko.',
    'before' => ' :attribute:n on oltava päivämäärä ennen :date:ta.',
    'before_or_equal' => ' :attribute:n on oltava päivämäärä, joka on ennen :date tai yhtä suuri kuin se.',
    'between' => [
        'numeric' => ' :attribute:n on oltava välillä :min ja :max.',
        'file' => ' :attribute:n on oltava :min– :max kilotavua.',
        'string' => ' :attribute:n on oltava :min- :max-merkin välillä.',
        'array' => ' :attribute:ssä on oltava :min– :max kohdetta.',
    ],
    'boolean' => ' :attribute-kentän on oltava tosi tai epätosi.',
    'confirmed' => ' :attribute-vahvistus ei täsmää.',
    'date' => ' :attribute ei ole kelvollinen päivämäärä.',
    'date_equals' => ' :attribute:n on oltava päivämäärä, joka on yhtä suuri kuin :date.',
    'date_format' => ' :attribute ei vastaa muotoa :format.',
    'different' => ' :attribute:n ja :other:n on oltava erilaisia.',
    'digits' => ' :attribute:n on oltava :digits numeroa.',
    'digits_between' => ' :attribute:n on oltava :min– :max numeroa.',
    'dimensions' => 'Kuvan :attribute mitat ovat virheelliset.',
    'distinct' => ' :attribute-kentällä on kaksoisarvo.',
    'email' => ' :attribute:n on oltava kelvollinen sähköpostiosoite.',
    'ends_with' => ' :attribute:n tulee päättyä johonkin seuraavista: :values.',
    'exists' => 'Valittu :attribute on virheellinen.',
    'file' => ' :attribute:n on oltava tiedosto.',
    'filled' => ' :attribute-kentällä on oltava arvo.',
    'gt' => [
        'numeric' => ' :attribute:n on oltava suurempi kuin :value.',
        'file' => ' :attribute:n on oltava suurempi kuin :value kilotavua.',
        'string' => ' :attribute:n on oltava suurempi kuin :value merkkiä.',
        'array' => ' :attribute:ssä on oltava enemmän kuin :value kohdetta.',
    ],
    'gte' => [
        'numeric' => ' :attribute:n on oltava suurempi tai yhtä suuri kuin :value.',
        'file' => ' :attribute:n on oltava suurempi tai yhtä suuri kuin :value kilotavua.',
        'string' => ' :attribute:n on oltava suurempi tai yhtä suuri kuin :value merkkiä.',
        'array' => ' :attribute:ssä on oltava vähintään :value kohdetta.',
    ],
    'image' => ' :attribute:n on oltava kuva.',
    'in' => 'Valittu :attribute on virheellinen.',
    'in_array' => ' :attribute-kenttää ei ole :other:ssa.',
    'integer' => ' :attribute:n on oltava kokonaisluku.',
    'ip' => ' :attribute:n on oltava kelvollinen IP-osoite.',
    'ipv4' => ' :attribute:n on oltava kelvollinen IPv4-osoite.',
    'ipv6' => ' :attribute:n on oltava kelvollinen IPv6-osoite.',
    'json' => ' :attribute:n on oltava kelvollinen JSON-merkkijono.',
    'lt' => [
        'numeric' => ' :attribute:n on oltava pienempi kuin :value.',
        'file' => ' :attribute:n on oltava pienempi kuin :value kilotavua.',
        'string' => ' :attribute:n on oltava pienempi kuin :value merkkiä.',
        'array' => 'Kohteessa :attribute on oltava vähemmän kuin :value kohdetta.',
    ],
    'lte' => [
        'numeric' => ' :attribute:n on oltava pienempi tai yhtä suuri kuin :value.',
        'file' => ' :attribute:n on oltava pienempi tai yhtä suuri kuin :value kilotavua.',
        'string' => ' :attribute:n on oltava pienempi tai yhtä suuri kuin :value merkkiä.',
        'array' => ' :attribute:ssä saa olla enintään :value kohdetta.',
    ],
    'max' => [
        'numeric' => ' :attribute ei saa olla suurempi kuin :max.',
        'file' => ' :attribute ei saa olla suurempi kuin :max kilotavua.',
        'string' => ' :attribute ei saa olla suurempi kuin :max merkkiä.',
        'array' => ' :attribute:ssä saa olla enintään :max kohdetta.',
    ],
    'mimes' => ' :attribute:n on oltava tiedostotyyppiä: :values.',
    'mimetypes' => ' :attribute:n on oltava tiedostotyyppiä: :values.',
    'min' => [
        'numeric' => ' :attribute:n on oltava vähintään :min.',
        'file' => ' :attribute:n on oltava vähintään :min kilotavua.',
        'string' => ' :attribute:ssä on oltava vähintään :min merkkiä.',
        'array' => ' :attribute:ssä on oltava vähintään :min kohdetta.',
    ],
    'multiple_of' => ' :attribute:n on oltava :value:n kerrannainen.',
    'not_in' => 'Valittu :attribute on virheellinen.',
    'not_regex' => ' :attribute-muoto on virheellinen.',
    'numeric' => ' :attribute:n on oltava numero.',
    'password' => 'Salasana on väärä.',
    'present' => ' :attribute-kentän on oltava läsnä.',
    'regex' => ' :attribute-muoto on virheellinen.',
    'required' => ' :attribute-kenttä on pakollinen.',
    'required_if' => 'Kenttä :attribute on pakollinen, kun :other on :value.',
    'required_unless' => 'Kenttä :attribute on pakollinen, ellei :other ole kohdassa :values.',
    'required_with' => 'Kenttä :attribute on pakollinen, kun :values on läsnä.',
    'required_with_all' => 'Kenttä :attribute on pakollinen, kun :values on läsnä.',
    'required_without' => 'Kenttä :attribute on pakollinen, kun :values ei ole läsnä.',
    'required_without_all' => 'Kenttä :attribute on pakollinen, kun mitään :values:sta ei ole.',
    'same' => ' :attribute:n ja :other:n on oltava samat.',
    'size' => [
        'numeric' => ' :attribute:n on oltava :size.',
        'file' => ' :attribute:n on oltava :size kilotavua.',
        'string' => ' :attribute:n on oltava :size merkkiä.',
        'array' => ' :attribute:n tulee sisältää :size kohdetta.',
    ],
    'starts_with' => ' :attribute:n täytyy alkaa jollakin seuraavista: :values.',
    'string' => ' :attribute:n on oltava merkkijono.',
    'timezone' => ' :attribute:n on oltava kelvollinen vyöhyke.',
    'unique' => ' :attribute on jo otettu.',
    'uploaded' => ' :attribute:n lataus epäonnistui.',
    'url' => ' :attribute-muoto on virheellinen.',
    'uuid' => ' :attribute:n on oltava kelvollinen UUID.',
    'custom' => [
        'attribute-name' => [
            'rule-name' => 'mukautettu viesti',
        ],
    ],
    'attributes' => [
    ],
];
